os:
  - windows

language: go
go:
  - 1.13.x

script:
  - go build -ldflags="-s -w"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: typer-go.exe
  skip_cleanup: true
  on:
    tags: true
